INSERT INTO MPA (MPA_NAME)
VALUES ('G');

INSERT INTO MPA (MPA_NAME)
VALUES ('PG');

INSERT INTO MPA (MPA_NAME)
VALUES ('PG-13');

INSERT INTO MPA (MPA_NAME)
VALUES ('R');

INSERT INTO MPA (MPA_NAME)
VALUES ('NC-17');

DELETE
FROM mpa
WHERE mpa_id > 5;